---
raw:
  data_directory: "/scratch/FPM/frogs_metagenomics/01-raw_data/Rana_temporaria"
  metadata: "./safe/metadata_PopLund.tsv"
  manifest: "manifest.tsv"
  threads: 24
size:
  num_min_seq: 281 #minimum number of sequences per sample
trim:  
  length: 300 #change values for the right cut of the reverse seq
directory_name:
  output_dir_cutadapt: "./cutadapt_PopLund/" #name of the directory after cutting the primers
  viz_dir_div: "./diversity_results_viz_PopLund/"
tables:
  freq_tbl: "artifact_PopLund/PopLund_freq_table.qza"
  freq_tbl_viz: "vizualizations_PopLund/PopLund_freq_table.qzv"
  freq_wctbl: "artifact_PopLund/w_chimeraPopLund_freq_table.qza"
  seqs_rep: "artifact_PopLund/PopLund_rep_seqs.qza"
  seqs_wcrep: "artifact_PopLund/w_chimeraPopLund_rep_seqs.qza" 
  seqs_rep_viz: "vizualizations_PopLund/PopLund_rep_seqs.qzv"
taxonomy:
  ref_taxa: "silva_ref_taxa.qza"
  ref_seq: "silva_ref_seqs.qza"
  classifier: "artifact_PopLund/silva_16S_classifier.qza"
  taxo_data: "artifact_PopLund/PopLund_taxonomy.qza"
illumina:
  primer_f: "CCTACGGGNGGCWGCAG"
  primer_r: "GACTACHVGGGTATCTAATCC"
diversity:
  max_depth: 1230 #check maximum frequency in freq_table
  raref_cap: 200 #see where in the alpha rarefraction it stabilizes
...
